### ISSUE TITLE
Multiplayer-Searching-Function

### ISSUE THREAD

**Issue by infinity-krapfen** [AntonDreher/Kakerlakenpoker-SE2-SS2021#3]
Der User sucht nach einem privaten Spiel.
Hier geht es um die Implementation der Funktion "Spiel finden".

**Comment by AntonDreher** [comment]
![image](https://user-images.githubusercontent.com/60618991/117534782-2f469280-aff3-11eb-9cac-965383df07ea.png)

**Comment by AntonDreher** [comment]
In einer ersten Version muss der Client, welcher sich zum Host-verbinden muss, noch seine IP-Adresse kennen. (Dies wird in einer späteren Version vom Server abgelöst).
